# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
permissions:                                
  contents: read                                                              # Workflow Having Read Permission for the contents
jobs:
  prisma_cloud_iac_DAST_scan:
    permissions:
      contents: read 			# read permissions for actions/checkout to fetch code from                  
      security-events: write                           # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read                               # only required for a private repository by github/CodeQL-action/upload-sarif to get the Action run status
      checks: write                              # Need write access to  PR checks to write the dastardly Results 
      id-token: write
    runs-on: ubuntu-latest                   # Action Runs on Github Runners(virtual machines) in this example it runs on Ubuntu   
    name: Run Prisma Cloud IaC Scan to check        
    steps:
      - name: Checkout repo                      #uses keyword  is used to specify the action that should be executed as part of a workflow
        uses: actions/checkout@v2            #it will check out the right version & branch that is associated with the GitHub push or pull request.
      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master     # It uses Bridgecrew action to run the Prisma Scans in Workflow
        env:				# indicates environment variable section
          PRISMA_API_URL: https://app.sg.prismacloud.io  
        with:
          api-key: ${{ secrets.BC_API_KEY }}     # Secrets key variable - securely access acesskey:secretkey to authenticate & run Prisma scan
          soft_fail: false                          # Soft_fail: false indicates Fail the build upon identifying vulnerabilities and true – indicates don’t fail the build
